version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck  # includes gosimple in v2
    - unused
    - misspell
    - unconvert
    - unparam
    - gocyclo
    - gocritic
    - revive
    - gosec
  settings:
    gocyclo:
      min-complexity: 15
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    revive:
      rules:
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
  exclusions:
    rules:
      # Test cleanup - standard Go idiom
      - path: _test\.go
        linters:
          - errcheck

      # Color output - return values intentionally ignored
      - path: internal/commands/
        text: "Error return value of .*(Printf|Print|Println)"
        linters:
          - errcheck
      - path: internal/commands/
        text: "G104.*Errors unhandled"
        linters:
          - gosec

      # Standard permissions for CLI data directories
      - linters:
          - gosec
        text: "G301|G306|G304"

      # Style suggestions - not enforced
      - linters:
          - gocritic
        text: "hugeParam|ifElseChain|unnamedResult|octalLiteral"

      # Test helper return value
      - path: _test\.go
        linters:
          - unparam

formatters:
  enable:
    - gofmt
    - goimports
